language: java
jdk: oraclejdk8
script:
  - cd centromere-parent
  - mvn -U clean test
notifications:
  email:
    recipients:
      - willoemler@gmail.com
    on_success: change
    on_failure: always
